### ISSUE TITLE
Czemu nie widzę w Issues postępów projektu ? 

### ISSUE THREAD

**Issue by jakubgalka** [Bartek321/Projekt-EiT-Godlewski#5]
jakie prace są prowadzone ?
Jakie zadania zostały zrealizowane ?
Gdzie jest code projektowy ? ostatni commit widzę 14 dni temu.

proszę o uzupełnienie wszystkiego w GitHubie !

**Comment by Bartek321** [comment]
Przepraszam za brak mojej aktywności na GitHubie. 
W ostatnim czasie miałem dużo innych zaliczeń, a obecnie zdaję egzaminy.
Czy nie byłoby problemem, gdybym zaktualizował projekt w najbliższy weekend?

**Comment by jakubgalka** [comment]
Projekt zaktualizować trzeba tak czy owak. Niestety , tak jak mówiłem na poczatku naszych spotkań, elementem projektu było monitorowanie postępów i utrzymywanie aktualnego projektu na platformie Githib. Niestety brak tej systematyczności spowoduje obnizenie oceny końcowej.

**Comment by Bartek321** [comment]
Wprowadziłem aktualizację w code i issues.
