### ISSUE TITLE
Technologie, narzędzia, SARMATA.

### ISSUE THREAD

**Issue by Bartek321** [Bartek321/Projekt-EiT-Godlewski#6]
Klient do SARMATY napisany jest w pythonie, dlatego też zdecydowałem, że projekt także tworzony będzie w tym języku.
Jako środowiska pracy korzystam z Microsoft Visual Studio.

Początkowo przy wysyłaniu dźwięku wykorzystywana miała być metoda "streaming". Nie wiem jednak jak prawidłowo z niej korzystać, a nie otrzymałem do tej pory żadnej informacji na ten temat od Pana Witkowskiego, z którym na ten temat rozmawiałem. Jednocześnie zauważyłem, że metoda ta nie za bardzo sprawdziłaby się w moim projekcie, ponieważ w przypadku, gdy system skoryguje tekst, który został już wklejony, jego zmiana byłaby problematyczna.
Zdecydowałem więc, że skorzystam z metody "sync". Dźwięk rejestrowany jest cały czas, jednak zapisywanie danych aktywowane jest przy wykryciu odpowiednio wysokiej amplitudy. Po chwili ciszy przerywane jest zapisywanie. Gdy jakieś dane są zapisane i minie odpowiednio długa chwila ciszy dane są wysyłane do SARAMATY.

**Comment by jakubgalka** [comment]
@Bartek321  - kiedy mógłbym zobaczyc demosntrację projektu ? Może w środę 9:30-15:30 ?

**Comment by Bartek321** [comment]
Rozumiem, że byłoby to tylko zaprezentowanie działania aplikacji i kodu? Czy musiałbym coś jeszcze przygotować? W środę mam również egzamin, więc mógłbym mieć z tym problem.
Jeżeli sama prezentacja, to mogłaby być to środa. Czy godzina 12 jest w porządku?

**Comment by jakubgalka** [comment]
Sama prezentacja. Tak 12:00 jest OK, wpisuję w kalendarz.
