### ISSUE TITLE
Zamknięcie Issues

### ISSUE THREAD

**Issue by jakubgalka** [Bartek321/Projekt-EiT-Godlewski#9]
@Bartek321 , po zakończeniu projektu proszę pozamykać pootwierane zadania, chyba, że planuje Pan jeszcze dalej nad nimi pracować.

Ps. Kto na EiT prowadzi lab projektowe ? Musze mu zgłosić Pańską ocenę bo ja nie mam dostępu do Waszego przedmiotu w Wirtualnym Dziekanacie.

**Comment by Bartek321** [comment]
Podejrzewam, że prawidłowi prowadzący dopiero zostaną przypisani w wirtualnym dziekanacie. Jeśli się nie mylę, to laboratoriami projektowymi zajmuję się dr Kołodziej.
Poprawiłem błąd ze spacją i dodałem możliwość usuwania. Opis dodam dopiero wieczorem, ponieważ mam jeszcze dzisiaj egzamin.
